name: Build
run-name: Build and deploy by @${{ github.actor }}

env:
  REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
  REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: github.repository == 'CytonicMC/Cytosis'
    runs-on: ubuntu-latest
    env:
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Publish Jar
        run: gradle --no-daemon publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

      - name: Publish Protocol
        run: gradle --no-daemon protocol:publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

  docker:
    if: github.repository == 'CytonicMC/Cytosis'
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Assemble Jar
        run: gradle --no-daemon fatJar
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

      - name: Login to GHCR
        run: echo $GHCR_TOKEN | docker login ghcr.io -u CytonicMC --password-stdin

      - name: Build and push Docker Image for multiple platforms
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/cytonicmc/cytosis:latest -f docker/basic/Dockerfile . --push

  build-plugins:
    if: github.repository == 'CytonicMC/Cytosis'
    needs: [ publish, docker ]
    runs-on: ubuntu-latest
    steps:
      - name: Build bedwars
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: '${{ secrets.ACTIONS_TOKEN }}'
          repository: 'CytonicMC/CytonicBedwars'
          event-type: 'trigger-workflow'
      - name: Build Lobby
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: '${{ secrets.ACTIONS_TOKEN }}'
          repository: 'CytonicMC/CytonicLobby'
          event-type: 'trigger-workflow'
      - name: Build GG
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: '${{ secrets.ACTIONS_TOKEN }}'
          repository: 'CytonicMC/GildedGorgeBase'
          event-type: 'trigger-workflow'
